services:
  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - crm-auto-escola-whats
      - crm-auto-escola-back

  crm-auto-escola-whats:
    build: ./crm-auto-escola-whats
    expose:
      - "3001"
    environment:
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome
      - WWEBJS_DATA_PATH=/data/.wwebjs_auth
    shm_size: "512mb"
    volumes:
      - wwebjs-data:/data
      - whats-media:/app/src/media
    restart: unless-stopped

  crm-auto-escola-back:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    working_dir: /app
    volumes:
      - ./crm-auto-escola-back/ExemploBackendDotNet:/app
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:5000
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=autoescola;Username=autoescola;Password=autoescola
    depends_on:
      - db
    command: >
      sh -c "
      dotnet --info
      && dotnet tool install --global dotnet-ef --version 9.0.0
      && export PATH=\"$$PATH:/root/.dotnet/tools\"
      && dotnet restore CRM.API/CRM.API.csproj
      && dotnet ef database update --project CRM.Persistence/CRM.Persistence.csproj --startup-project CRM.API/CRM.API.csproj
      && dotnet build CRM.API/CRM.API.csproj -v normal
      && dotnet run --project CRM.API/CRM.API.csproj --urls http://0.0.0.0:5000"
    ports:
      - "5000:5000"
    restart: unless-stopped
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: autoescola
      POSTGRES_USER: autoescola
      POSTGRES_PASSWORD: autoescola
    ports:
      - "5431:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  db-data:
  wwebjs-data:
  whats-media:
  caddy_data:
  caddy_config:
